export const CREATE_COLOR_REQUEST = "CREATE_COLOR_REQUEST";
export const CREATE_COLOR_SUCCESS = "CREATE_COLOR_SUCCESS";
export const CREATE_COLOR_FAIL = "CREATE_COLOR_FAIL";
export const CREATE_COLOR_RESET = "CREATE_COLOR_RESET";

export const COLOR_LIST_REQUEST = "COLOR_LIST_REQUEST";
export const COLOR_LIST_SUCCESS = "COLOR_LIST_SUCCESS";
export const COLOR_LIST_FAIL = "COLOR_LIST_FAIL";
export const COLOR_LIST_RESET = "COLOR_LIST_RESET";

export const COLOR_DELETE_SUCCESS = "COLOR_DELETE_SUCCESS";
